language: python
dist: bionic
python:
  - "3.7"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.venv

branches:
  only:
    - "master"

before_install:
  - pip install poetry

install:
  - poetry install

before_script:
  - poetry config virtualenvs.in-project true

jobs:
  include:
    - name: flake8
      script: poetry run flake8 pii_recognition
    - name: mypy
      script: poetry run mypy --config-file pyproject.toml pii_recognition
    - name: unittest
      script: poetry run pytest pii_recognition
    - name: integration test
      script: poetry run pytest tests