name: Python CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - task: Lint with flake8
            run: flake8 pii_recognition tests
          - task: Type check
            run: mypy --config-file pyproject.toml pii_recognition
          - task: Unit tests
            run: pytest pii_recognition
          - task: Integration tests
            run: pytest tests 
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Get full python version
        id: full-python-version
        run: |
          echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info[:3]))")
      - name: Cache .cache dir
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('poetry.lock') }}
      - name: ${{ matrix.task }}
        run: |
          pip install poetry
          poetry install
          poetry run ${{ matrix.run }}
