name: Python CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - task: Lint with flake8
            run: flake8 pii_recognition
          - task: Type Check
            run: mypy --config-file pyproject.toml pii_recognition
          - task: Unit Tests
            run: pytest pii_recognition
          - task: Integration Tests
            run: poetry run pytest tests 
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
      - name: Cache .cache dir
        uses: actions/cache@v2
        with:
          path: "$HOME/.cache"    
          key: ${{ runner.os }}-cache-dir-${{ hashFiles('poetry.lock') }}          
          restore-keys: |
            ${{ runner.os }}-cache-dir-
            ${{ runner.os }}-
      - name: ${{ matrix.task }}
        run: |
          pip install poetry
          poetry install
          poetry run ${{ matrix.run }}
